// Document-number format shared with the backend: PREFIX-YY-MM-DD-000001
// (e.g. ORD-26-06-15-000001 for orders, REQ-26-06-15-000001 for stock requests).
// The 6-digit sequence resets to 000001 each calendar month.
//
// Order/request numbers are generated by the server and shown read-only in the UI
// (there is no input field for them), so they can't be edited by hand. These
// validators are available for defensive checks wherever a number is consumed.

export const ORDER_NUMBER_PATTERN = /^ORD-\d{2}-\d{2}-\d{2}-\d{6}$/;
export const REQUEST_NUMBER_PATTERN = /^REQ-\d{2}-\d{2}-\d{2}-\d{6}$/;

export function isValidOrderNumber(value: string | null | undefined): boolean {
  return !!value && ORDER_NUMBER_PATTERN.test(value);
}

export function isValidRequestNumber(value: string | null | undefined): boolean {
  return !!value && REQUEST_NUMBER_PATTERN.test(value);
}
