using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SalesApp.Api.Models;

namespace SalesApp.Api.Services;

public interface IInvoiceService
{
    /// <summary>Builds an item-wise PDF invoice for an order (Customer + Items must be loaded).</summary>
    byte[] Generate(Order order);
}

public class InvoiceService : IInvoiceService
{
    public byte[] Generate(Order order)
    {
        var doc = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(36);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(t => t.FontSize(10));

                page.Header().Row(row =>
                {
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().Text("Sales Application").Bold().FontSize(18);
                        c.Item().Text("Tax Invoice").FontSize(12).FontColor(Colors.Blue.Medium);
                    });
                    row.ConstantItem(180).AlignRight().Column(c =>
                    {
                        c.Item().Text($"Invoice: {order.OrderNumber}").Bold();
                        c.Item().Text($"Date: {order.OrderDate:dd-MM-yyyy HH:mm}");
                        if (order.DeliveryDate is not null)
                            c.Item().Text($"Delivery: {order.DeliveryDate:dd-MM-yyyy HH:mm}");
                    });
                });

                page.Content().PaddingVertical(12).Column(col =>
                {
                    col.Spacing(10);

                    col.Item().Column(c =>
                    {
                        c.Item().Text("Bill To").Bold().FontColor(Colors.Grey.Darken1);
                        c.Item().Text(order.Customer?.Name ?? "-").Bold();
                        if (!string.IsNullOrWhiteSpace(order.Customer?.Phone)) c.Item().Text($"Phone: {order.Customer!.Phone}");
                        if (!string.IsNullOrWhiteSpace(order.Customer?.Email)) c.Item().Text($"Email: {order.Customer!.Email}");
                        if (!string.IsNullOrWhiteSpace(order.Customer?.Address)) c.Item().Text(order.Customer!.Address!);
                    });

                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(c =>
                        {
                            c.ConstantColumn(28);   // #
                            c.RelativeColumn(4);    // Item
                            c.RelativeColumn(1.2f); // Qty
                            c.RelativeColumn(2);    // Unit Price
                            c.RelativeColumn(2);    // Line Total
                        });
                        table.Header(h =>
                        {
                            h.Cell().Element(Head).Text("#");
                            h.Cell().Element(Head).Text("Item");
                            h.Cell().Element(Head).AlignRight().Text("Qty");
                            h.Cell().Element(Head).AlignRight().Text("Unit Price");
                            h.Cell().Element(Head).AlignRight().Text("Total");
                        });
                        var i = 1;
                        foreach (var it in order.Items)
                        {
                            table.Cell().Element(Cell).Text((i++).ToString());
                            table.Cell().Element(Cell).Text(it.Item?.Name ?? "-");
                            table.Cell().Element(Cell).AlignRight().Text(it.Quantity.ToString());
                            table.Cell().Element(Cell).AlignRight().Text(Money(it.UnitPrice));
                            table.Cell().Element(Cell).AlignRight().Text(Money(it.LineTotal));
                        }
                    });

                    col.Item().AlignRight().Column(c =>
                    {
                        c.Spacing(2);
                        c.Item().Text($"Total: {Money(order.TotalAmount)}").Bold().FontSize(12);
                        c.Item().Text($"Paid: {Money(order.PaidAmount)}");
                        c.Item().Text($"Remaining: {Money(order.RemainingAmount)}");
                    });

                    if (!string.IsNullOrWhiteSpace(order.Notes))
                        col.Item().PaddingTop(6).Text($"Notes: {order.Notes}").FontColor(Colors.Grey.Darken1);

                    // Current order & payment status, shown at the end of the invoice.
                    col.Item().PaddingTop(6).Column(c =>
                    {
                        c.Item().Text($"Order Status: {order.Status}").Bold();
                        c.Item().Text($"Payment Status: {order.PaymentStatus}").Bold();
                    });
                });

                page.Footer().AlignCenter().Text(t =>
                    t.Span($"Generated by Sales Application on {DateTime.UtcNow:dd-MM-yyyy}").FontColor(Colors.Grey.Medium));
            });
        });
        return doc.GeneratePdf();
    }

    // "Rs." instead of the ₹ glyph so it always renders regardless of the PDF font.
    private static string Money(decimal v) => $"Rs. {v:N2}";

    private static IContainer Head(IContainer c) =>
        c.Background(Colors.Grey.Lighten3).PaddingVertical(5).PaddingHorizontal(4).DefaultTextStyle(t => t.Bold());
    private static IContainer Cell(IContainer c) =>
        c.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingVertical(4).PaddingHorizontal(4);
}
